//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;

namespace DataBaseLayer
{
    public partial class AWorksLTEntities : DbContext
    {
        public AWorksLTEntities()
            : base("name=AWorksLTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BuildVersion> BuildVersions { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductDescription> ProductDescriptions { get; set; }
        public DbSet<ProductModel> ProductModels { get; set; }
        public DbSet<ProductModelProductDescription> ProductModelProductDescriptions { get; set; }
        public DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeaders { get; set; }
    
        public virtual ObjectResult<AndOrOperator_Result> AndOrOperator()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(AndOrOperator_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AndOrOperator_Result>("AndOrOperator");
        }
    
        public virtual ObjectResult<CInnerJoin_Result> CInnerJoin()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(CInnerJoin_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CInnerJoin_Result>("CInnerJoin");
        }
    
        public virtual ObjectResult<GreaterThanOrEqual_Result> GreaterThanOrEqual(Nullable<System.DateTime> date)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(GreaterThanOrEqual_Result).Assembly);
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GreaterThanOrEqual_Result>("GreaterThanOrEqual", dateParameter);
        }
    
        public virtual ObjectResult<MultipleTables_Result> MultipleTables()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(MultipleTables_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MultipleTables_Result>("MultipleTables");
        }
    
        public virtual ObjectResult<SelectAll_Result> SelectAll()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectAll_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAll_Result>("SelectAll");
        }
    
        public virtual ObjectResult<SelectAllAlt_Result> SelectAllAlt()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectAllAlt_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllAlt_Result>("SelectAllAlt");
        }
    
        public virtual ObjectResult<SelectDistinct_Result> SelectDistinct()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectDistinct_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDistinct_Result>("SelectDistinct");
        }
    
        public virtual ObjectResult<SelectMultipleDistinct_Result> SelectMultipleDistinct()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectMultipleDistinct_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMultipleDistinct_Result>("SelectMultipleDistinct");
        }
    
        public virtual ObjectResult<SelectStar_Result> SelectStar()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectStar_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectStar_Result>("SelectStar");
        }
    
        public virtual ObjectResult<Sum_Result> Sum()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Sum_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sum_Result>("Sum");
        }
    
        public virtual ObjectResult<Where3Conditions_Result> Where3Conditions(string name, Nullable<int> productID)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(Where3Conditions_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Where3Conditions_Result>("Where3Conditions", nameParameter, productIDParameter);
        }
    
        public virtual ObjectResult<WhereBetweenValues_Result> WhereBetweenValues(Nullable<int> idval1, Nullable<int> idval2)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereBetweenValues_Result).Assembly);
    
            var idval1Parameter = idval1.HasValue ?
                new ObjectParameter("Idval1", idval1) :
                new ObjectParameter("Idval1", typeof(int));
    
            var idval2Parameter = idval2.HasValue ?
                new ObjectParameter("Idval2", idval2) :
                new ObjectParameter("Idval2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereBetweenValues_Result>("WhereBetweenValues", idval1Parameter, idval2Parameter);
        }
    
        public virtual ObjectResult<WhereClauseOneArgument_Result> WhereClauseOneArgument(string name, string color)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereClauseOneArgument_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereClauseOneArgument_Result>("WhereClauseOneArgument", nameParameter, colorParameter);
        }
    
        public virtual ObjectResult<WhereComparisonOperator_Result> WhereComparisonOperator(string name, Nullable<int> productID)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereComparisonOperator_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereComparisonOperator_Result>("WhereComparisonOperator", nameParameter, productIDParameter);
        }
    
        public virtual ObjectResult<WhereEqualsInteger_Result> WhereEqualsInteger(Nullable<int> price)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereEqualsInteger_Result).Assembly);
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereEqualsInteger_Result>("WhereEqualsInteger", priceParameter);
        }
    
        public virtual ObjectResult<WhereEqualsString_Result> WhereEqualsString()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereEqualsString_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereEqualsString_Result>("WhereEqualsString");
        }
    
        public virtual ObjectResult<WhereLikeString_Result> WhereLikeString(string name)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereLikeString_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereLikeString_Result>("WhereLikeString", nameParameter);
        }
    
        public virtual ObjectResult<WhereListValues_Result> WhereListValues(string name)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereListValues_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereListValues_Result>("WhereListValues", nameParameter);
        }
    
        public virtual ObjectResult<WhereSeveralConditions_Result> WhereSeveralConditions(string name, string color)
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereSeveralConditions_Result).Assembly);
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereSeveralConditions_Result>("WhereSeveralConditions", nameParameter, colorParameter);
        }
    
        public virtual ObjectResult<WhereSimpleEquality_Result> WhereSimpleEquality()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(WhereSimpleEquality_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WhereSimpleEquality_Result>("WhereSimpleEquality");
        }
    
        public virtual ObjectResult<RevenueCalcuation_Result> RevenueCalcuation()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(RevenueCalcuation_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RevenueCalcuation_Result>("RevenueCalcuation");
        }
    
        public virtual ObjectResult<SelectSubset_Result> SelectSubset()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectSubset_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectSubset_Result>("SelectSubset");
        }
    
        public virtual ObjectResult<SelectWhereNoParams_Result> SelectWhereNoParams()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(SelectWhereNoParams_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectWhereNoParams_Result>("SelectWhereNoParams");
        }
    
        public virtual ObjectResult<InnerJoinWhereMethod_Result> InnerJoinWhereMethod()
        {
            ((IObjectContextAdapter)this).ObjectContext.MetadataWorkspace.LoadFromAssembly(typeof(InnerJoinWhereMethod_Result).Assembly);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InnerJoinWhereMethod_Result>("InnerJoinWhereMethod");
        }
    }
}
